team_builder/team_builder/urls.py
import notifications.urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path, re_path

from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),

    # Account stuff (sign-up, sign-in, etc)
    path('accounts/signin/', views.SignInView.as_view(), name='signin'),
    path('accounts/signout/', LogoutView.as_view(), name='signout'),
    path('accounts/signup/', views.SignUpView.as_view(), name='signup'),

    # Profile URLs
    path('profile/<int:profile_id>/', views.ProfileDetailView.as_view(),
         name='profile'),
    path('profile/<int:profile_id>/update/',
         views.ProfileUpdateView.as_view(), name='profile_update'),

    # Project creation, update, etc
    path('projects/list/', views.ProjectView.as_view(),
         name='projects'),

    re_path(r'^projects/list/(?P<filter_type>own|join|member)/$',
            views.ProjectView.as_view(), name='projects_filter'),

    path('projects/filter/', views.ProjectFilterView.as_view(),
         name='projects_skill_filter'),

    path('projects/detail/<int:project_id>/',
         views.ProjectDetailView.as_view(),
         name='project_detail'),

    path('projects/create/',
         views.ProjectCreateView.as_view(),
         name='project_create'),

    path('projects/<int:project_id>/update/',
         views.ProjectUpdateView.as_view(),
         name='project_update'),

    # Position creation, update, etc
    path('projects/<int:project_id>/position/add/',
         views.PositionAddView.as_view(),
         name='position_add'),

    path('position/<int:position_id>/detail/',
         views.PositionDetailView.as_view(),
         name='position_detail'),

    path('position/<int:position_id>/update/',
         views.PositionUpdateView.as_view(),
         name='position_update'),

    path('position/<int:position_id>/delete/',
         views.PositionDeleteView.as_view(),
         name='position_delete'),

    path('search/', views.SearchView.as_view(), name='search'),

    # Applying for participation, approving/denying or clearing
    path('participant/<int:position_id>/apply/',
         views.ParticipantCreateView.as_view(), name='participant_create'),

    re_path(r'^participant/(?P<participant_id>\d+)/(?P<action>approve|reject|retire|leave)/$',
            views.participant_update_view, name='participant_update'),

    path('skill/<int:skill_id>/', views.SkillDetailView.as_view(),
         name='skill_detail'),

    re_path('skill/(?P<referrer>user|position)/(?P<referrer_id>\d+)/add/',
            views.SkillCreateView.as_view(), name='skill_add'),

    # Notifications
    path('notifications/', include(notifications.urls,
                                   namespace='notifications'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'team_builder.views.handler404'

team_builder/team_builder/models.py
import os
import uuid
from datetime import date

from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone


def get_file_path(instance, filename):
    """
    Formatting file path of avatar data
    :param instance: Model instance
    :param filename: Name of uploaded file
    :return: File path for upload_to
    """
    ext = filename.split('.')[-1]
    today = date.today().strftime("%Y/%m/%d")
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('avatars', today, filename)


class UserManager(BaseUserManager):

    def create_user(self, email, username, password):
        if not email:
            raise ValueError('Email Required')
        print(username)
        user = self.models(
            email=self.normalize_email(email),
            username=username)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, username, password):
        if not email:
            raise ValueError('Email Required')

        user = self.models(
            email=self.normalize_email(email),
            username=username)
        user.set_password(password)
        user.is_superuser = True
        user.save()
        return user


class Skill(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=40, unique=True)
    bio = models.CharField(max_length=300, null=True)
    avatar = models.ImageField(null=True, upload_to=get_file_path)
    date_joined = models.DateField(default=timezone.now)
    is_staff = models.BooleanField(default=False)
    profile = models.CharField(max_length=300, blank=True)
    skills = models.ManyToManyField(Skill, blank=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.username

    def get_short_name(self):
        return self.username

    def get_long_name(self):
        return '{} {}'.format(self.username, self.email)

    def get_absolute_url(self):
        return reverse('profile', args=[str(self.id)])


class Project(models.Model):
    name = models.CharField(max_length=40, unique=True)
    description = models.CharField(max_length=200)
    url = models.URLField(null=True, blank=True)
    start_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(null=True)
    owner = models.ForeignKey(User, on_delete=models.PROTECT)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('project_detail', args=[str(self.id)])


class Position(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    position_name = models.CharField(max_length=50)
    head_count = models.IntegerField(default=1)
    related_skills = models.ManyToManyField(Skill, blank=True)
    participants = models.ManyToManyField(User, through='Participant')

    def __str__(self):
        return self.position_name

    def get_absolute_url(self):
        return reverse('position_detail', args=[self.id])

    def get_member_count(self):
        """
        :return: Number of participants for a given position
        """
        return self.participant_set.filter(status='member').count()


class Participant(models.Model):
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, default='pending')
    created_date = models.DateTimeField(default=timezone.now)
    start_date = models.DateTimeField(null=True)
    end_date = models.DateTimeField(null=True)

team_builder/templates/index.html
{% extends 'layout.html' %}
{% load rules %}

{% block body %}
{% with request.resolver_match as view_detail %}

{% if not request.user.is_authenticated %}
<div class="jumbotron">
    <h1 class="display-4">Hello, stranger!</h1>
    <p>Seems like you're either new here or not signed in!<br>
        You can view projects but won't be able to view profiles until you're signed in.<br></p>
    <hr class="my-4">
    Click below to get started.<br>
    <form action="{% url 'signup' %}" method="post">
        {% csrf_token %}
        <button type="submit">Sign Up</button>
    </form>
    <form action="{% url 'signin' %}" method="post">
        {% csrf_token %}
        <button type="submit">Sign In</button>
    </form>
</div>
{% endif %}

{% if object_list %}
<table class="u-full-width circle--table table-striped">
<thead>
  <tr>
    <th>Project</th>
    <th>Owner</th>
    <th>Positions</th>
    <th></th>
  </tr>
</thead>
<tbody>
  {% for project in object_list %}
  {% has_perm 'team_builder.edit_project' user project as can_edit_project %}
  {% has_perm 'team_builder.leave_project' user project as can_leave_project %}
  {% has_perm 'team_builder.join_project' user project as can_join_project %}
  <tr class="clickable-row" data-href="{{ project.get_absolute_url }}">
      <td class="nowrap">{{ project.name }}</td>
      <td><a href="{% url 'profile' profile_id=project.owner.id %}">{{ project.owner.username }}</td>
      <td>{{ project.position_set.all|join:"," }}</td>
      <td class="vert-aligned">{% include "projects/project_control_buttons.html" %}</td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% elif view_detail.view_name == 'projects_filter' and view_detail.kwargs.filter_type != 'own'%}
<div class="jumbotron">
    <h1 class="display-4">There doesn't seem to be anything here yet</h1>
      <form action="{% url 'home' %}" method="get">
          {% csrf_token %}
          <button type="submit">Go Home</button>
      </form>
</div>
{% else %}
<div class="jumbotron">
    <h1 class="display-4">There aren't any projects here yet!</h1>
    <p>How about adding your own?</p><br>
      <form action="{% url 'project_create' %}" method="get">
          {% csrf_token %}
          <button type="submit">New Project+</button>
      </form>
</div>
{% endif %}

{% endwith %}

{% endblock %}

team_builder/templates/layout.html
{% load static %}
{% load notifications_tags %}
{% notifications_unread as unread_count %}

<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Team Supreme</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONTS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static "css/global.css" %}">
  <link rel="stylesheet" href="{% static "css/variables.css" %}">


  <!-- JS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
  <script type="text/javascript" src="{% static "js/autogrow.js" %}"></script>
  <script type="text/javascript" src="{% static "js/global.js" %}"></script>
  <script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
  {% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}

</head>
<body>
  <header class="circle--header">
    <div class="bounds">
      <div class="circle--fluid">
        <div class="circle--fluid--cell">
          <a href="{% url 'home' %}"><img src="{% static 'images/icons/connection.32.png' %}"></a>
          <!--
          <h1 class="hide-text circle--logo"><a class="logo" href="{% url 'home' %}">Circle</a></h1>
          -->
        </div>
        <div class="circle--fluid--cell circle--fluid--primary">
          <div class="circle--search">
            <form name="search" action="{% url 'search' %}" method="get">
                {% csrf_token %}
              <input type="text" name="search_q" placeholder="Search Projects..." />
              <button>
                <svg version="1.1" class="search" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 12 12" xml:space="preserve">
                  <path d="M12,10.6L8.3,6.9C8.7,6.2,9,5.4,9,4.5C9,2,7,0,4.5,0S0,2,0,4.5S2,9,4.5,9c0.9,0,1.7-0.3,2.4-0.7l3.7,3.7L12,10.6z M2,4.5
                  C2,3.1,3.1,2,4.5,2S7,3.1,7,4.5C7,5.9,5.9,7,4.5,7S2,5.9,2,4.5z"/>
                </svg>
              </button>
            </form>
          </div>
        </div>
        <div class="circle--fluid--cell circle--fluid--secondary">
          <nav>
            <ul class="circle--inline">
              {% if request.user.is_authenticated %}
                <li><a href="{% url 'signout' %}">Sign Out</a></li>
              {% else %}
              <li><a href="{% url 'signup' %}">Sign Up</a></li>
              <li><a href="{% url 'signin' %}">Sign In</a></li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>

  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        {% if user.is_authenticated %}
          <li><a class="selected" href="{% url 'profile' profile_id=request.user.id %}">Profile</a></li>
          <li><a href="{% url 'projects_filter' filter_type='own' %}">Own</a></li>
          <li><a href="{% url 'projects_filter' filter_type='member' %}">Member</a></li>
          <li><a href="{% url 'projects_filter' filter_type='join' %}">Join</a></li>
        {% endif %}
          <li><a href="{% url 'projects_skill_filter' %}">Filter</a></li>
        {% if user.is_authenticated %}
          <li>
            <a href="{% url 'notifications:all' %}">
              <img src="{% static 'images/icons/open-envelope-24.png' %}">{% live_notify_badge badge_class="badge" %}
            </a>
          </li>
        {% endif %}

      </ul>
    </nav>
  </div>

  <div class="bounds circle--page">
    <div class="grid-70">
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}

{% block body %}

{% endblock %}

</div>

<div class="grid-25 grid-push-5">
  {% if request.user.is_authenticated %}
        <h3>Signed in: {{ request.user.username }}!</h3>
      <form class="new_project_button" action="{% url 'project_create' %}" method="get">
          {% csrf_token %}
          <button type="submit">New Project+</button>
      </form><br><br>
    {% if request.user.avatar %}
      <div class="circle--secondary--module">
        <div class="circle--primary--avatar">
          <img src="{{ request.user.avatar.url }}">
        </div>
      </div>
    {% endif %}
  {% endif %}
</div>

</div>

</body>
</html>

team_builder/templates/profile.html
{% extends 'layout.html' %}

{% block body %}

<table class="td-header">
    <tr>
        <td>
            <h2>Profile</h2>
        </td>
        <td class="icon-on-right">
            {% if request.user == object %}
            <form action="{% url 'profile_update' profile_id=object.id %}" method="get">
                <button type="submit">Edit</button>
            </form>
            {% endif %}
        </td>
    </tr>
</table>

<h1 class="circle--input--h1">{{ object.username }}</h1>

{% if object != request.user %}
    {% if object.avatar %}
          <img src="{{ object.avatar.url }}">
    {% endif %}
{% endif %}

<h2>Bio</h2>
<div class="circle--article--body">
    {% if object.bio %}
    {{ object.bio }}
    {% else %}
    <i>User has not added a bio yet</i>
    {% endif %}
</div>

<h2>Profile</h2>

<div class="circle--article--body">
    {% if object.profile %}
    {{ object.profile }}
    {% else %}
    <i>User has not added a profile yet</i>
    {% endif %}
</div>

<h2>Own Projects</h2>

<table class="u-full-width circle--table table-striped">
    <thead>
        <tr>
            <th>Project Title</th>
            <th class="circle--cell--right">Project Needs</th>
        </tr>
    </thead>
    <tbody>
        {% for project in object.project_set.all %}
        <tr class="clickable-row" data-href="{% url 'project_detail' project_id=project.id %}">
            <td>
                <h5>{{ project.name }}</h5>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">{{ project.position_set.all|join:", " }}</span>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% if current_positions|length > 0 %}
<h2>Current Positions</h2>
<table class="u-full-width circle--table table-striped">
    <thead>
        <tr>
            <th>Project Title</th>
            <th class="circle--cell--right">Position</th>
        </tr>
    </thead>
    <tbody>
        {% for position in current_positions.all %}
        <tr class="clickable-row" data-href="{% url 'project_detail' project_id=position.project.id %}">
            <td>
                <h5>{{ position.project.name }}</h5>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">{{ position.position_name }}</span>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}

{% if past_positions|length > 0 %}
<h2>Past Positions</h2>
<table class="u-full-width circle--table table-striped">
    <thead>
        <tr>
            <th>Project Title</th>
            <th class="circle--cell--right">Position</th>
        </tr>
    </thead>
    <tbody>
        {% for position in past_positions.all %}
        <tr class="clickable-row" data-href="{% url 'project_detail' project_id=position.project.id %}">
            <td>
                <h5>{{ position.project.name }}</h5>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">{{ position.position_name }}</span>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}

<h2>Skills</h2>

<table class="u-full-width circle--table table-striped" title="Skills">
    <thead>
        <tr>
            <th>Skill</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for skill in object.skills.all %}
        <tr class="clickable-row" data-href="{% url 'skill_detail' skill_id=skill.id %}">
            <td>
              <h5>{{ skill.name }}</h5>
            </td>
            <td>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

team_builder/templates/profile_update.html
{% extends 'layout.html' %}

{% block body %}

    <h1>Profile...</h1>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Save</button>
    </form>

    {% if request.user == object %}
    <form action="{% url 'skill_add' referrer='user' referrer_id=user.id %}" method="get">
      {% csrf_token %}
      <button type="submit">Add Skill</button>
      </form>
    {% endif %}

{% endblock %}

team_builder/templates/search.html
{% extends 'layout.html' %}
{% load rules %}

{% block body %}

<h1>Search Results</h1>

<h2>Results matching query: {{ search_terms }}</h2>
{% if project_results|length > 0 %}
<h3>Projects</h3>
<table class="u-full-width circle--table table-striped">
<thead>
  <tr>
    <th>Project</th>
    <th>Owner</th>
    <th>Positions</th>
    <th></th>
  </tr>
</thead>
<tbody>
  {% for project in project_results %}
  <tr class="clickable-row" data-href="{{ project.get_absolute_url }}">
      <td>{{ project.name }}</td>
      <td><a href="{% url 'profile' profile_id=project.owner.id %}">{{ project.owner.username }}</td>
      <td>{{ project.position_set.all|join:"," }}</td>
      <td>{% include "projects/project_control_buttons.html" %}</td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% endif %}

{% if position_results|length > 0 %}
<h3>Positions</h3>
<table class="u-full-width circle--table table-striped">
    <thead>
        <tr>
            <th>Position</th>
            <th>Project</th>
            <th>Skills Needed</th>
        </tr>
    </thead>
    <tbody>
        {% for position in position_results %}
        <tr class="clickable-row" data-href="{{ position.get_absolute_url }}">
            <td>
                <h5>{{ position }}</h5>
            </td>
            <td>
                {{ position.project }}
            </td>
            <td>
                {{ position.related_skills.all|join:", " }}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}

{% if user_results|length > 0 %}
<h3>Users</h3>
<table class="u-full-width circle--table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Projects</th>
            <th>Skills</th>
        </tr>
    </thead>
    <tbody>
        {% for user in user_results %}
            <tr class="clickable-row" data-href="{{ user.get_absolute_url }}">
                <td>
                    <h5>
                        {{ user.username }}</h5>
                </td>
                <td>
                    {{ user.project_set.all|join:", " }}
                </td>
                <td>
                    {{ user.skills.all|join:", " }}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>{% endif %}


{% endblock %}